### PR TITLE
bind a resize event to adjust the footer

### PR DESCRIPTION
**Pull request by rubene**
* Because when the user resize the page the footer does not
stick to the button. Added a resize event and refactor to have
the events just call methods to adjust the footer.

http://ama-digital.myjetbrains.com/youtrack/issue/TECHDBT-1041

### CODE REVIEW

**Comment by weyermannx** [comment]
:elephant: :elephant: :elephant: 
be aware another pull request is going to bump the gem to 1.2 - https://github.com/amaabca/ama_layout/pull/36

**Comment by MathieuGilbert** [comment]
:wave: Rebased master

**Comment by darkodosenovic** [comment]
:elephant: :elephant:  :elephant: 

Be aware of versioning

**Comment by darkodosenovic** [comment]
:elephant: :elephant:  :elephant:

**Comment by darkodosenovic** [comment]
:elephant: :elephant: :elephant:

**Pull request closed without merging**
