### PR TITLE
Insurance navigation

### PR DESCRIPTION
**Pull request by darkodosenovic**
:elephant: :art:

### CODE REVIEW

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by rubene** [comment]
:hankey: 
check version
rebase master

**Comment by adamrmelnyk** [comment]
rebase again :hankey:

**Comment by darkodosenovic** [comment]
:wave:

**Comment by kathleenAMA** [comment]
:art: :art: :art:

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by darkodosenovic** [comment]
:poop:
Merge master, there is no certain date for this to be pushed since the insurance app is not working at this time. Closing this PR and should be reopened once it is ready to go.

**Pull request closed without merging**
