### PR TITLE
TECHDBT-1236 - Remove Images/Stylesheets

### PR DESCRIPTION
**Pull request by jessedoyle**
:elephant: :art:

* Images and stylesheets now live in
  https://github.com/amaabca/ama_styles.
* Bump to version `5.0.0`.

### CODE REVIEW

**Comment by MathieuGilbert** [comment]
📖

**Comment by MathieuGilbert** [comment]
💩  not ready for review

**Comment by rubene** [comment]
:wave:

**Comment by MathieuGilbert** [comment]
To summarize the changes, did you just `git rm app/assets/images app/assets/stylesheets` (in addition to the 4 edited files)?

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by MathieuGilbert** [comment]
:art: :art: :art:

**Pull request merged**
