### PR TITLE
fixing broken links

### PR DESCRIPTION
**Pull request by kathleenAMA**
This PR addresses the issue here: https://ama-digital.myjetbrains.com/youtrack/issue/YA-1038#

Not sure if there is a rails helper for the road reports link. If there is just let me know and I'll change it. 

Tagging design as well. 
@kaytcampbell

### CODE REVIEW

**Comment by kaytcampbell** [comment]
:art: :art: :art: looks good to me

**Comment by rubene** [comment]
Did a search on the rails envs there is no entry for road reports site url, we should probably open a bug to add it, this change will have to update all apps envs, so we also we the correct url for different environments 
```
AMAABCA_SITE_URL=https://ama.ab.ca
API_SITE_URL=https://api.ama.ab.ca
ASSETS_SITE_URL=https://modules.ama.ab.ca
DRIVEREDONLINE_SITE_URL=https://driveredonline.ama.ab.ca
FORMS_SITE_URL=https://forms.ama.ab.ca
FORMS2_SITE_URL=https://forms2.ama.ab.ca
GATEKEEPER_SITE_URL=https://auth.ama.ab.ca
INSURANCE_SITE_URL=https://insurance-oa.ama.ab.ca
MEMBERSHIP_SITE_URL=https://membership.ama.ab.ca
YOURACCOUNT_SITE_URL=https://youraccount.ama.ab.ca
```

@jbabe what do you think about merging this now and open a bug or make the update part of this?

**Comment by darkodosenovic** [comment]
:elephant: :elephant: :elephant:

**Comment by kathleenAMA** [comment]
:wave:

**Comment by kaytcampbell** [comment]
:art: :art: :art: :elephant: :elephant: :elephant:

**Pull request merged**
