### PR TITLE
Add missing link for members in billing late

### PR DESCRIPTION
**Pull request by rubene**
* Bug: http://ama-digital.myjetbrains.com/youtrack/issue/MEMBR-1131

### CODE REVIEW

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by jbabe** [comment]
:hankey: we need to set this up to run on Travis CI

**Comment by rubene** [comment]
:wave:

**Comment by darkodosenovic** [comment]
:elephant: :elephant: :elephant:

**Pull request merged**
