### PR TITLE
VSTS-795 rails 5 nav update

### PR DESCRIPTION
**Pull request by zoiec**
🐘

- Added outstanding balance check to display outstanding balance nav
- Added test for navigation helper

### CODE REVIEW

**Comment by darkodosenovic** [comment]
🐘 🐘 🐘

**Comment by zoiec** [comment]
👋

**Comment by zoiec** [comment]
👋  Added membership_payment_path for use in apps to redirect users with outstanding balance direct to the membership payment page

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by zoiec** [comment]
👋  Changed Outstanding balance url

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by zoiec** [comment]
👋  Changed helper url and pay outstanding balance url

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant: You and Jesse are both updating the version number to the same thing... so race to merge first!

**Comment by zoiec** [comment]
👋  Version change to 6.8.0.pre

**Comment by darkodosenovic** [comment]
🐘 🐘 🐘

**Pull request merged**
