### PR TITLE
Changing help link 

### PR DESCRIPTION
**Pull request by darkodosenovic**
:elephant: :art:
Changing help link to point to Gatekeeper help file. 
* Your account help file to be removed in the future.

### CODE REVIEW

**Comment by rubene** [comment]
:elephant: :elephant: :elephant:

**Comment by darkodosenovic** [comment]
:wave:

**Comment by rubene** [comment]
:elephant: :elephant: :elephant:

**Comment by darkodosenovic** [comment]
:wave;

**Comment by kathleenAMA** [comment]
:art: :art: :art:

**Comment by rubene** [comment]
:elephant: :elephant: :elephant:

**Pull request merged**
