### PR TITLE
Add new components for sign in and create pages

### PR DESCRIPTION
**Pull request by kaytcampbell**
:art: :elephant:
Adds the hero and feature components, also organizes the fonts a bit.

### CODE REVIEW

**Comment by rubene** [comment]
:book:

**Comment by kaytcampbell** [comment]
@sineade I had them in the HTML originally, I couldn't get them to work either way.

**Comment by rubene** [comment]
🐘 🐘 🐘

**Comment by kaytcampbell** [comment]
:wave: made changes after elephants, need a re-review pls

**Comment by mvandenbeuken** [comment]
🐘 🐘 🐘

**Comment by sineade** [comment]
:art: :art: :art:

**Pull request merged**
