### PR TITLE
Insurance fixes

### PR DESCRIPTION
**Pull request by sineade**
:art:
This PR contains the fixes for the following two bugs.

https://ama-digital.myjetbrains.com/youtrack/issue/INSGW-73
https://ama-digital.myjetbrains.com/youtrack/issue/INSGW-65

### CODE REVIEW

**Comment by MathieuGilbert** [comment]
@sineade Do you have screenshots of the fixed display in IE?

**Comment by sineade** [comment]
bs_win10_ie_11 0

bs_win10_ie_11 0 copy

:wave: screenshots from browser stack of fixes for ie.

**Comment by jessedoyle** [comment]
:art::art::art:

**Comment by jessedoyle** [comment]
:art::art::art:

**Pull request merged**
