### PR TITLE
Added has_outstanding_balance to nav

### PR DESCRIPTION
**Pull request by zoiec**
🐘 

- Added outstanding balance check to display outstanding balance nav
- Added test for navigation helper

### CODE REVIEW

**Comment by MathieuGilbert** [comment]
💩 
Looks good, just need the `version.rb` updated.

**Comment by zoiec** [comment]
👋

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by zoiec** [comment]
👋  Added membership_payment_path for use in apps to redirect users with outstanding balance direct to the membership payment page

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by zoiec** [comment]
👋  Changed Outstanding balance url

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by darkodosenovic** [comment]
:poop: We have to change url on this one

**Comment by zoiec** [comment]
👋  Changed helper url and pay outstanding balance url

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by zoiec** [comment]
👋  Version change to 5.8.0 to be merged after Jesse

**Comment by darkodosenovic** [comment]
🐘 🐘 🐘

**Pull request merged**
