### PR TITLE
Remove nav hover

### PR DESCRIPTION
**Pull request by kaytcampbell**
Takes out the hover on the side nav in favour of a click. Also changes the top level nav items to have "My" in front of them (except Esso which will get changed when we launch the rewards overview page).

### CODE REVIEW

**Comment by weyermannx** [comment]
:elephant: :elephant: :elephant:

**Comment by adamrmelnyk** [comment]
:hankey: This one is bumping from 24 to 26. was there one in between?

**Comment by kaytcampbell** [comment]
@adamrmelnyk yeah there's this one that isn't merged in yet https://github.com/amaabca/ama_layout/pull/49/files

**Comment by kaytcampbell** [comment]
:wave: will need a design review as well @kathleenAMA

**Comment by adamrmelnyk** [comment]
:elephant: :elephant: :elephant:

**Comment by kathleenAMA** [comment]
:art: :art :art:

**Pull request merged**
