### PR TITLE
Had to add partial to helper to fix failing tests in all the apps

### PR DESCRIPTION
**Pull request by sineade**
:elephant:

Previously updated ama_layout but did not have partial, when I pushed to all the other apps the tests failed because of this. This will fix those failing tests.

### CODE REVIEW

**Comment by jessedoyle** [comment]
:elephant::elephant::elephant:

**Comment by jessedoyle** [comment]
:hankey: there are a few tests to fix in this repo as well!

**Comment by sineade** [comment]
:wave:

**Comment by jessedoyle** [comment]
:elephant::elephant::elephant:

**Pull request merged**
