### PR TITLE
This will bold the current navigation

### PR DESCRIPTION
**Pull request by weyermannx**
🐘 
* Well, it's bold and a nice blue color to show the currently selected
navigation item
* This broke when we switched to the API Model for navigation
* Adding to ama_layout because it already has javascript, in any case I
think this will require the update of all the apps

* had to parse out google tag manager params
* VSTS 1612
* https://amaabca.visualstudio.com/dx_technical_debt/_workitems?id=1612&_a=edit

### PR Review Checklist
To be completed by the person who opens the PR. Use strikethroughs for items that are not applicable in list.
- [x] I have reviewed my own PR to check syntax & logic, removed unnecessary/old code, made sure everything aligns with our style guide and BEM.
- [x] Any applicable version numbers have been updated.
- [x] I've tested on mobile, tablet, and desktop, as well as across all of the browsers we support.
- [x] I've proof-read all text for legibility, proper grammar, punctuation, and capitalization (titlecase).
- [x] I have written a detailed PR message explaining what is being changed and why
- [x] I’ve linked to any relevant VSTS tickets
- [x] I’ve added the appropriate review symbols to my PR - (elephant) for dev review, (art) for design

### CODE REVIEW

**Comment by jessedoyle** [comment]
:book:

**Comment by jessedoyle** [comment]
Nice implementation! I've noticed it also bolds headers that may have the same url:

screen shot 2018-01-03 at 9 14 16 am

Is this intended?

**Comment by jessedoyle** [comment]
:hankey:

**Comment by weyermannx** [comment]
not entirely, but unavoidable. I think given they're both the same link, it's fine. That said, we may want to evaluate whether we want to have a double link like that in the first place

**Comment by weyermannx** [comment]
:wave:

**Comment by jessedoyle** [comment]
:wave:

**Comment by darkodosenovic** [comment]
:book:

**Comment by darkodosenovic** [comment]
🐘 🐘 🐘

**Pull request merged**
