### PR TITLE
Rails 5 - VSTS 438 - User Notifications - Frontend

### PR DESCRIPTION
**Pull request by jessedoyle**
:elephant:

This is a repeat of #205, but for the `rails-5` branch.

### CODE REVIEW

**Comment by MathieuGilbert** [comment]
📖

**Comment by MathieuGilbert** [comment]
:fatfingers:

**Comment by MathieuGilbert** [comment]
:elephant: :elephant: :elephant:

**Comment by kaytcampbell** [comment]
:art: :art: :art:

**Pull request merged**
