### PR TITLE
Sineads online account refresh rebased

### PR DESCRIPTION
**Pull request by jbabe**
@kaytcampbell and @kathleenAMA I pulled master into Sinead's branch - so I'll close https://github.com/amaabca/ama_layout/pull/110. Can you guys check to see if resolving the merge conflicts broke anything?

### CODE REVIEW

**Comment by kaytcampbell** [comment]
@jbabe does it work for you locally? I'm getting a syntax error.

**Comment by jbabe** [comment]
yeah - i am too. I'll take a look.

**Comment by jbabe** [comment]
@kaytcampbell - I removed too much when resolving the merge conflicts - I've reverted to the master version for that part of the file to get it to run: https://github.com/amaabca/ama_layout/pull/112/commits/897064a5c2510bfda0480ce5102a130c7016d7e7

So It should work for you now - and I can drop the `cta-box` stuff later cause I think we don't need it right?

**Comment by jbabe** [comment]
Closing this cause #110 is the right one.

**Pull request closed without merging**
